spring.application.name=La-Curva-League
path.json_jornadas=data/jornadas/
path.json_jugadores=data/jugadores/
path.json_misters=data/misters/
spring.thymeleaf.encoding=UTF-8
# Ruta al archivo físico (sin la extensión .mv.db)
spring.datasource.url=jdbc:h2:file:C:/Users/Matias/Desktop/Spring/la-curva-league/data/lacurvadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Importante para que no borre tus datos al arrancar
spring.jpa.hibernate.ddl-auto=update

# Muestra las consultas SQL en la consola
spring.jpa.show-sql=true
# Formatea el SQL para que sea legible
spring.jpa.properties.hibernate.format_sql=true
# Muestra los valores de los parámetros (?)
logging.level.org.hibernate.orm.jdbc.bind=trace


