spring.application.name=La-Curva-League
path.json_jornadas=data/jornadas/
path.json_jugadores=data/jugadores/
path.json_misters=data/misters/
spring.thymeleaf.encoding=UTF-8

# Envía los datos en grupos de 100 en lugar de 1 uno a uno
spring.jpa.properties.hibernate.jdbc.batch_size=100
# Reordena los inserts para que el batch funcione con tablas relacionadas
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.datasource.hikari.data-source-properties.reWriteBatchedInserts=true

spring.profiles.active=local
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.datasource.hikari.data-source-properties.preparedStatementCacheQueries=0
spring.datasource.hikari.data-source-properties.preparedStatementCacheSizeMiB=0



